spring.application.name=Online-Video-Rental-System
spring.profiles.active=dev
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
management.endpoints.web.exposure.include=health,info,metrics

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.repositories.enabled=false
spring.cache.redis.time-to-live=1500000
management.endpoint.health.show-details=always
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525

spring.mail.username=ebbaea3759aad6
spring.mail.password=0289381f98a82d

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true