spring.datasource.url=jdbc:postgresql://dpg-d810ftmgvqtc73dvgu4g-a.oregon-postgres.render.com:5432/video_682x
spring.datasource.username=user
spring.datasource.password=cHIgwD4k2w0oB5tUVvKsPL0PJwpSbl8d
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
server.tomcat.threads.max=20
spring.datasource.hikari.maximum-pool-size=5
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525

spring.mail.username=ebbaea3759aad6
spring.mail.password=0289381f98a82d

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true