spring.datasource.url=jdbc:postgresql://dpg-d810ftmgvqtc73dvgu4g-a.oregon-postgres.render.com:5432/video_682x
spring.datasource.username=user
spring.datasource.password=cHIgwD4k2w0oB5tUVvKsPL0PJwpSbl8d
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect